// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ8m8Sqm2CwCZakt2DgcIIf-DSQdXoLW4',
    appId: '1:426145841989:web:ef386ae07637117766342c',
    messagingSenderId: '426145841989',
    projectId: 'desafio6semestre',
    authDomain: 'desafio6semestre.firebaseapp.com',
    storageBucket: 'desafio6semestre.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrYhfKoCltZH9SKghIGnBXnhmxtzOIKRY',
    appId: '1:426145841989:android:fce207749395a54466342c',
    messagingSenderId: '426145841989',
    projectId: 'desafio6semestre',
    storageBucket: 'desafio6semestre.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDme2H5EBnAhHuMjruYuLQyTL8hY7_FkEI',
    appId: '1:426145841989:ios:79ff21187a75521b66342c',
    messagingSenderId: '426145841989',
    projectId: 'desafio6semestre',
    storageBucket: 'desafio6semestre.appspot.com',
    iosBundleId: 'br.unaerp.desafio6etapa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDme2H5EBnAhHuMjruYuLQyTL8hY7_FkEI',
    appId: '1:426145841989:ios:8b9b36deec1c845d66342c',
    messagingSenderId: '426145841989',
    projectId: 'desafio6semestre',
    storageBucket: 'desafio6semestre.appspot.com',
    iosBundleId: 'br.unaerp.desafio6etapa.RunnerTests',
  );
}
